to_do/source/ToDo/urls.py
from django.conf.urls import patterns, url
from .views import ToDoCreate, ToDoDone, ToDoList

urlpatterns = patterns('',
    url(r'^$', ToDoList.as_view(), name='todo-list',),
    url(r'^add$', ToDoCreate.as_view(), name='todo-add',),
    url(r'^done/(?P<pk>\d+)/$', ToDoDone.as_view(), name='todo-done',),
)

to_do/source/source/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^', include('ToDo.urls', namespace='todo')),
    url(r'^admin/', include(admin.site.urls)),
)

to_do/source/ToDo/models.py
"""
    Models for the ToDo app.
"""
from django.db import models
from django.core.urlresolvers import reverse


class ToDo(models.Model):
    """ Main Model. """
    created = models.DateField(auto_now_add=True, editable=False)
    todo = models.TextField()
    compleated = models.DateField(editable=False, null=True)

    def get_absolute_url(self):
        """ what is my name again? """
        return reverse('todo:todo-list')

to_do/source/ToDo/forms.py
"""
    We need a form for created for the todos
"""
from django import forms
from .models import ToDo


class ToDoForm(forms.ModelForm):
    """ Only want to set the ccs controls. """

    todo = forms.CharField(widget=forms.Textarea(
        attrs={'cols': 10, 'rows': 5, 'class': 'form-control'}
    ))

    class Meta:
        """ Meta options go here. """
        model = ToDo
        exclude = ('created', 'compleated')

to_do/source/ToDo/views.py
"""
    Here are the ToDo views.
    I Chose to go with class based views as they are bit more difficult to
    build and manage.
"""
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic import ListView
from django.core.urlresolvers import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from datetime import datetime
from .models import ToDo
from .forms import ToDoForm


class ToDoCreate(CreateView):
    """ Lets create a todo. """
    model = ToDo
    form_class = ToDoForm
    success_url = reverse_lazy('todo:todo-list')


class ToDoDone(UpdateView):
    """ Lets mark a todo as done. """
    model = ToDo
    fields = []
    success_url = reverse_lazy('todo:todo-list')

    def get(self, request, *args, **kwargs):
        """ Over rideing 'get' to mark the todo done from a get. """
        super(ToDoDone, self).get(request, *args, **kwargs)
        self.object = self.get_object()
        self.object.compleated = datetime.now()
        self.object.save()
        return HttpResponseRedirect(reverse('todo:todo-list'))


class ToDoList(ListView):
    """ Lets list it out baby! """
    template_name = 'ToDo/index.html'
    queryset = ToDo.objects.filter(compleated__isnull=True)

to_do/source/ToDo/templates/ToDo/base.html
{% load staticfiles %}
<html>
    <head>
        <link href="{% static 'bootstrap/css/bootstrap.min.css' %}"
                rel="stylesheet" media="screen">
    </head>

    <body>
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
        <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    </body>
</html>

to_do/source/ToDo/templates/ToDo/index.html
{% extends 'ToDo/base.html' %}

{% block content %}
    <div class="row">
        <h1 class="col-xs-6">Your ToDo's</h1>
    </div>

    <div class="row">
        <ul>
            <div class="col-xs-4">
                {% for todo in object_list %}
                    <li>{{ todo.created }}: {{ todo.todo }} : <a href={% url 'todo:todo-done' todo.id %}>done</a></li>
                {% endfor %}
            </div>
        </ul>
    </div>

    <div class="row">
        &nbsp;<!--wanted a filler row-->
    </div>

    <div class="row">
        <div class="col-xs-6">
            <a href="{% url 'todo:todo-add' %}">add ToDo</a>
        </div>
    </div>

{% endblock %}

to_do/source/ToDo/templates/ToDo/todo_form.html
{% extends 'ToDo/base.html' %}

{% block content %}
    <div class="row">
        <h1 class="col-xs-6">New ToDo</h1>
    </div>

    <div class="row">
        <form action="" method="post" class="form-horizontal">{% csrf_token %}
            <div class="form-group">
                <div class="col-xs-4 col-md-offset-1">
                    {{ form.as_p }}
                    <input type="submit" value="Create" />
                </div>
            </div>
        </form>
    </div>
{% endblock %}